// Physics Theories and Models Data
const physicsData = {
  "name": "Physics as known today",
  "year": 2026,
  "children": [
    {
      "name": "Classical Mechanics",
      "year": 1687,
      "children": [
        {
          "name": "Newtonian Mechanics",
          "year": 1687,
          "children": [
            {"name": "Newton's Laws of Motion", "year": 1687, "summary": "Three fundamental laws describing the relationship between motion and forces.", "people": ["Isaac Newton"], "tags": [{"name": "force", "explanation": "These laws describe how forces cause changes in motion and the relationship between force, mass, and acceleration."}], "papers": [{"title": "Philosophiæ Naturalis Principia Mathematica", "link": "https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica"}]},
            {"name": "Universal Gravitation", "year": 1687, "summary": "Every particle attracts every other particle with a force proportional to their masses.", "people": ["Isaac Newton"], "tags": [{"name": "force", "explanation": "Describes the gravitational force that acts between all masses in the universe."}]},
            {"name": "Conservation of Momentum", "year": 1644, "summary": "Total momentum of a closed system remains constant in the absence of external forces.", "people": ["René Descartes"]},
            {"name": "Conservation of Energy", "year": 1847, "summary": "Energy cannot be created or destroyed, only transformed from one form to another.", "people": ["Julius Robert von Mayer", "James Prescott Joule"]}
          ]
        },
        {
          "name": "Analytical Mechanics",
          "year": 1788,
          "children": [
            {"name": "Lagrangian Formulation", "year": 1788, "summary": "Mechanics reformulated using kinetic and potential energy in a single function.", "people": ["Joseph-Louis Lagrange"]},
            {"name": "Hamiltonian Formulation", "year": 1834, "summary": "Mechanics expressed in terms of position and momentum coordinates.", "people": ["William Rowan Hamilton"]},
            {"name": "Action Principle", "year": 1744, "summary": "Physical systems follow paths that minimize or maximize the action integral.", "people": ["Pierre Louis Maupertuis"]},
            {"name": "Canonical Transformations", "year": 1834, "summary": "Coordinate transformations that preserve the form of Hamilton's equations.", "people": ["William Rowan Hamilton"]}
          ]
        },
        {
          "name": "Continuum Mechanics",
          "year": 1822,
          "children": [
            {"name": "Fluid Dynamics", "year": 1755, "summary": "Study of fluids in motion and the forces acting on them.", "people": ["Leonhard Euler", "Daniel Bernoulli"]},
            {"name": "Elasticity Theory", "year": 1822, "summary": "Behavior of materials that return to original shape after deformation.", "people": ["Claude-Louis Navier", "Augustin-Louis Cauchy"]},
            {"name": "Wave Propagation", "year": 1747, "summary": "How waves travel through different media and interact with boundaries.", "people": ["Jean le Rond d'Alembert"]},
            {"name": "Navier-Stokes Equations", "year": 1822, "summary": "Fundamental equations describing the motion of viscous fluid substances.", "people": ["Claude-Louis Navier", "George Gabriel Stokes"]}
          ]
        }
      ]
    },
    {
      "name": "Quantum Physics",
      "year": 1900,
      "children": [
        {
          "name": "Quantum Mechanics",
          "year": 1925,
          "children": [
            {"name": "Schrödinger Equation", "year": 1926, "summary": "Fundamental equation describing how quantum states evolve over time.", "people": ["Erwin Schrödinger"], "tags": [{"name": "time", "explanation": "The equation describes the time evolution of quantum states, showing how wave functions change over time."}], "papers": [{"title": "An Undulatory Theory of the Mechanics of Atoms and Molecules", "link": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.28.1049"}], "nobel": 1933},
            {"name": "Heisenberg Uncertainty Principle", "year": 1927, "summary": "Fundamental limit to precision of simultaneous measurement of complementary properties.", "people": ["Werner Heisenberg"], "papers": [{"title": "Über den anschaulichen Inhalt der quantentheoretischen Kinematik und Mechanik", "link": "https://en.wikipedia.org/wiki/Uncertainty_principle"}], "nobel": 1932},
            {"name": "Wave-Particle Duality", "year": 1924, "summary": "Concept that all matter exhibits both wave and particle properties.", "people": ["Louis de Broglie"], "nobel": 1929},
            {"name": "Quantum Entanglement", "year": 1935, "summary": "Phenomenon where particles become correlated and share quantum states.", "people": ["Albert Einstein", "Boris Podolsky", "Nathan Rosen"]}
          ]
        },
        {
          "name": "Quantum Field Theory",
          "year": 1927,
          "children": [
            {"name": "Standard Model", "year": 1975, "summary": "Theory describing three of the four fundamental forces and all known elementary particles.", "people": ["Sheldon Glashow", "Abdus Salam", "Steven Weinberg"], "tags": [{"name": "force", "explanation": "The Standard Model describes three of the four fundamental forces: electromagnetic, weak nuclear, and strong nuclear forces."}], "nobel": 1979},
            {"name": "Quantum Electrodynamics", "year": 1948, "summary": "Quantum field theory of electromagnetism describing interactions of light and matter.", "people": ["Richard Feynman", "Julian Schwinger", "Sin-Itiro Tomonaga"], "tags": [{"name": "force", "explanation": "Describes the electromagnetic force at the quantum level, governing interactions between charged particles and photons."}], "nobel": 1965},
            {"name": "Quantum Chromodynamics", "year": 1973, "summary": "Theory of the strong nuclear force that binds quarks and gluons.", "people": ["Murray Gell-Mann", "Harald Fritzsch", "Heinrich Leutwyler"], "tags": [{"name": "force", "explanation": "Describes the strong nuclear force that binds quarks together to form protons, neutrons, and other hadrons."}], "nobel": 1969},
            {"name": "Electroweak Theory", "year": 1967, "summary": "Unified description of electromagnetic and weak nuclear forces.", "people": ["Sheldon Glashow", "Abdus Salam", "Steven Weinberg", "Gerardus 't Hooft", "Martinus J. G. Veltman"], "tags": [{"name": "force", "explanation": "Unifies the electromagnetic and weak nuclear forces into a single theoretical framework."}], "nobel": 1979}
          ]
        },
        {
          "name": "Information Theory",
          "year": 1948,
          "children": [
            {"name": "Shannon Entropy", "year": 1948, "summary": "Mathematical measure of uncertainty or information content in a message or system. Fundamental concept in information theory that quantifies the amount of information needed to describe a random variable.", "people": ["Claude Shannon"]},
            {"name": "Channel Capacity", "year": 1948, "summary": "Maximum rate at which information can be reliably transmitted over a communication channel, as determined by Shannon's channel coding theorem.", "people": ["Claude Shannon"]}
          ]
        },
        {
          "name": "Quantum Information",
          "year": 1980,
          "children": [
            {"name": "Quantum Computing", "year": 1982, "summary": "Computing paradigm that uses quantum mechanical phenomena like superposition and entanglement to perform computations.", "people": ["Richard Feynman", "Paul Benioff", "Yuri Manin"]},
            {"name": "Quantum Cryptography", "year": 1984, "summary": "Cryptographic protocols that use quantum mechanical properties to secure communication.", "people": ["Charles Bennett", "Gilles Brassard"]},
            {"name": "Bell's Theorem", "year": 1964, "summary": "Theorem proving that no local hidden variable theory can reproduce all predictions of quantum mechanics.", "people": ["John Stewart Bell"], "nobel": 2022},
            {"name": "Superdeterminism", "year": 1985, "summary": "Interpretation of quantum mechanics suggesting that apparent randomness is actually deterministic, with initial conditions of the universe correlated in a way that makes quantum measurements appear random. Proposed as a way to explain quantum correlations without violating locality.", "people": ["John Stewart Bell"]},
            {"name": "Quantum Teleportation", "year": 1993, "summary": "Process of transferring quantum information from one location to another using entanglement.", "people": ["Charles Bennett", "Gilles Brassard", "Claude Crépeau", "Richard Jozsa", "Asher Peres", "William Wootters"], "nobel": 2022}
          ]
        }
      ]
    },
    {
      "name": "Relativity",
      "year": 1905,
      "children": [
        {
          "name": "Special Relativity",
          "year": 1905,
          "children": [
            {"name": "Lorentz Transformations", "year": 1904, "summary": "Mathematical transformations that relate space and time coordinates between different inertial reference frames.", "people": ["Hendrik Lorentz"], "tags": [{"name": "time", "explanation": "These transformations show how time coordinates change when moving between different reference frames in special relativity."}], "nobel": 1902},
            {"name": "Time Dilation", "year": 1905, "summary": "Phenomenon where time passes slower for objects moving relative to an observer.", "people": ["Albert Einstein"], "tags": [{"name": "time", "explanation": "Directly describes how time itself is affected by relative motion, with time passing slower for moving objects."}], "papers": [{"title": "On the Electrodynamics of Moving Bodies", "link": "https://en.wikipedia.org/wiki/Annus_Mirabilis_papers"}], "nobel": 1921},
            {"name": "Length Contraction", "year": 1905, "summary": "Phenomenon where the length of an object appears shorter when moving relative to an observer.", "people": ["Albert Einstein"]},
            {"name": "Mass-Energy Equivalence", "year": 1905, "summary": "Principle that mass and energy are equivalent and can be converted into each other, expressed as E=mc².", "people": ["Albert Einstein"], "papers": [{"title": "Does the Inertia of a Body Depend Upon Its Energy Content?", "link": "https://en.wikipedia.org/wiki/Annus_Mirabilis_papers"}]}
          ]
        },
        {
          "name": "General Relativity",
          "year": 1915,
          "children": [
            {"name": "Einstein Field Equations", "year": 1915, "summary": "Set of equations describing how matter and energy curve spacetime.", "people": ["Albert Einstein"], "tags": [{"name": "force", "explanation": "These equations describe gravity as a force resulting from the curvature of spacetime caused by matter and energy."}], "papers": [{"title": "The Field Equations of Gravitation", "link": "https://en.wikipedia.org/wiki/Einstein_field_equations"}]},
            {"name": "Black Holes", "year": 1916, "summary": "Regions of spacetime where gravity is so strong that nothing can escape.", "people": ["Karl Schwarzschild", "Albert Einstein"], "nobel": 2020},
            {"name": "Holographic Principle", "year": 1993, "summary": "Principle suggesting that the description of a volume of space can be encoded on a lower-dimensional boundary. Inspired by black hole thermodynamics, it proposes that all information within a region can be represented as a hologram on its boundary.", "people": ["Gerardus 't Hooft", "Leonard Susskind"]},
            {"name": "Gravitational Waves", "year": 1916, "summary": "Ripples in spacetime caused by accelerating massive objects.", "people": ["Albert Einstein"], "nobel": 2017},
            {"name": "Cosmological Models", "year": 1917, "summary": "Theoretical frameworks describing the large-scale structure and evolution of the universe.", "people": ["Albert Einstein", "Willem de Sitter", "Alexander Friedmann"], "tags": [{"name": "time", "explanation": "These models describe how the universe evolves over cosmological time scales, from the Big Bang to the present and future."}]}
          ]
        },
        {
          "name": "Relativistic Mechanics",
          "year": 1905,
          "children": [
            {"name": "Relativistic Kinematics", "year": 1905, "summary": "Study of motion in the absence of forces, accounting for relativistic effects.", "people": ["Albert Einstein"]},
            {"name": "Relativistic Dynamics", "year": 1905, "summary": "Study of motion under the influence of forces, incorporating relativistic corrections.", "people": ["Albert Einstein"]},
            {"name": "Minkowski Spacetime", "year": 1908, "summary": "Four-dimensional mathematical model combining three-dimensional space with time into a single continuum.", "people": ["Hermann Minkowski"], "tags": [{"name": "time", "explanation": "Unifies space and time into a four-dimensional spacetime continuum, where time is treated as a dimension on equal footing with spatial dimensions."}]},
            {"name": "Twin Paradox", "year": 1911, "summary": "Thought experiment demonstrating time dilation where a traveling twin ages slower than a stationary twin.", "people": ["Albert Einstein", "Paul Langevin"], "tags": [{"name": "time", "explanation": "Demonstrates the real-world consequences of time dilation, showing how time passes differently for observers in relative motion."}]}
          ]
        }
      ]
    },
    {
      "name": "Thermodynamics",
      "year": 1850,
      "children": [
        {
          "name": "Classical Thermodynamics",
          "year": 1850,
          "children": [
            {"name": "Laws of Thermodynamics", "year": 1850, "summary": "Four fundamental laws governing energy, entropy, and temperature in thermodynamic systems.", "people": ["Rudolf Clausius", "William Thomson"], "tags": [{"name": "time", "explanation": "The second law establishes the arrow of time by stating that entropy increases over time, giving time its directionality."}, {"name": "exergy", "explanation": "The laws of thermodynamics, particularly the second law, are fundamental to understanding exergy, which measures the maximum useful work obtainable from a system."}]},
            {"name": "Entropy", "year": 1865, "summary": "Measure of disorder or randomness in a system, central to the second law of thermodynamics.", "people": ["Rudolf Clausius"], "tags": [{"name": "time", "explanation": "Entropy's increase over time defines the arrow of time, explaining why processes are irreversible and why we remember the past but not the future."}, {"name": "exergy", "explanation": "Entropy is directly related to exergy destruction - the greater the entropy generation, the more exergy is destroyed in a process."}]},
            {"name": "Heat Engines", "year": 1824, "summary": "Devices that convert thermal energy into mechanical work through cyclic processes.", "people": ["Sadi Carnot"], "tags": [{"name": "exergy", "explanation": "Heat engines convert exergy (available energy) into useful work, with efficiency limited by exergy destruction due to irreversibilities."}]},
            {"name": "Carnot Cycle", "year": 1824, "summary": "Theoretical reversible thermodynamic cycle that defines the maximum possible efficiency for a heat engine.", "people": ["Sadi Carnot"], "tags": [{"name": "exergy", "explanation": "The Carnot cycle represents the ideal case where all exergy is converted to work with no exergy destruction, achieving maximum exergy efficiency."}]},
            {"name": "Exergy", "year": 1956, "summary": "Maximum useful work obtainable from a system as it reaches equilibrium with its environment. Also known as available energy or availability.", "people": ["Zoran Rant"], "tags": [{"name": "exergy", "explanation": "Exergy is the measure of the maximum useful work that can be extracted from a system, measuring energy quality and potential for conversion to work."}]}
          ]
        },
        {
          "name": "Statistical Mechanics",
          "year": 1871,
          "children": [
            {"name": "Boltzmann Distribution", "year": 1871, "summary": "Probability distribution describing the statistical behavior of particles in thermal equilibrium.", "people": ["Ludwig Boltzmann"]},
            {"name": "Fermi-Dirac Statistics", "year": 1926, "summary": "Statistical distribution describing particles with half-integer spin that obey the Pauli exclusion principle.", "people": ["Enrico Fermi", "Paul Dirac"]},
            {"name": "Bose-Einstein Statistics", "year": 1924, "summary": "Statistical distribution describing particles with integer spin that can occupy the same quantum state.", "people": ["Satyendra Nath Bose", "Albert Einstein"]},
            {"name": "Partition Function", "year": 1902, "summary": "Mathematical function that encodes the statistical properties of a thermodynamic system in equilibrium.", "people": ["Josiah Willard Gibbs"]}
          ]
        },
        {
          "name": "Non-Equilibrium Thermodynamics",
          "year": 1931,
          "children": [
            {"name": "Onsager reciprocal relations", "year": 1931, "summary": "Symmetry relations between transport coefficients in systems near thermodynamic equilibrium.", "people": ["Lars Onsager"], "tags": [{"name": "exergy", "explanation": "Onsager relations describe irreversible processes that lead to exergy destruction in non-equilibrium systems."}]},
            {"name": "Fluctuation-Dissipation Theorem", "year": 1951, "summary": "Theorem connecting the response of a system to external perturbations with its internal fluctuations.", "people": ["Herbert Callen", "Theodore Welton"], "tags": [{"name": "exergy", "explanation": "Fluctuations and dissipation processes are directly related to exergy destruction in thermodynamic systems."}]},
            {"name": "Brownian Motion", "year": 1905, "summary": "Random motion of particles suspended in a fluid resulting from collisions with surrounding molecules.", "people": ["Albert Einstein", "Marian Smoluchowski"]},
            {"name": "Diffusion Processes", "year": 1905, "summary": "Process by which particles spread from regions of high concentration to regions of low concentration.", "people": ["Albert Einstein", "Adolf Fick"], "tags": [{"name": "exergy", "explanation": "Diffusion processes involve exergy destruction as concentration gradients are dissipated, reducing the system's capacity to do work."}]}
          ]
        }
      ]
    },
    {
      "name": "Electromagnetism",
      "year": 1865,
      "children": [
        {
          "name": "Classical Electrodynamics",
          "year": 1865,
          "children": [
            {"name": "Maxwell's Equations", "year": 1865, "summary": "Four fundamental equations describing electricity, magnetism, and their relationship.", "people": ["James Clerk Maxwell"], "papers": [{"title": "A Dynamical Theory of the Electromagnetic Field", "link": "https://en.wikipedia.org/wiki/A_Dynamical_Theory_of_the_Electromagnetic_Field"}]},
            {"name": "Electromagnetic Waves", "year": 1865, "summary": "Oscillating electric and magnetic fields that propagate through space.", "people": ["James Clerk Maxwell", "Heinrich Hertz"]},
            {"name": "Lorentz Force", "year": 1895, "summary": "Force experienced by a charged particle moving through electric and magnetic fields.", "people": ["Hendrik Lorentz"], "tags": [{"name": "force", "explanation": "Describes the electromagnetic force acting on charged particles moving through electric and magnetic fields."}]},
            {"name": "Gauss's Law", "year": 1835, "summary": "Relationship between electric flux through a closed surface and enclosed charge.", "people": ["Carl Friedrich Gauss"]}
          ]
        },
        {
          "name": "Optics",
          "year": 1801,
          "children": [
            {"name": "Wave Optics", "year": 1801, "summary": "Branch of optics that treats light as a wave, explaining phenomena like interference and diffraction.", "people": ["Thomas Young"]},
            {"name": "Geometric Optics", "year": 1637, "summary": "Branch of optics that treats light as rays, describing reflection and refraction using geometric principles.", "people": ["René Descartes"]},
            {"name": "Interference", "year": 1801, "summary": "Phenomenon where two or more waves superpose to form a resultant wave of greater or lower amplitude.", "people": ["Thomas Young"]},
            {"name": "Diffraction", "year": 1665, "summary": "Bending and spreading of waves around obstacles or through apertures, characteristic of wave behavior.", "people": ["Francesco Maria Grimaldi", "Christiaan Huygens"]}
          ]
        },
        {
          "name": "Plasma Physics",
          "year": 1928,
          "children": [
            {"name": "Magnetohydrodynamics", "year": 1942, "summary": "Study of the dynamics of electrically conducting fluids in magnetic fields.", "people": ["Hannes Alfvén"]},
            {"name": "Plasma Waves", "year": 1928, "summary": "Oscillations and waves that propagate through plasma, a state of matter with free charged particles.", "people": ["Irving Langmuir", "Lewi Tonks"]},
            {"name": "Fusion Theory", "year": 1950, "summary": "Theoretical framework describing nuclear fusion, the process of combining light atomic nuclei to form heavier ones.", "people": ["Lyman Spitzer"]},
            {"name": "Solar Wind Models", "year": 1958, "summary": "Theoretical models describing the continuous stream of charged particles emitted from the Sun's corona.", "people": ["Eugene Parker"]}
          ]
        }
      ]
    },
    {
      "name": "Particle Physics",
      "year": 1930,
      "children": [
        {
          "name": "Elementary Particles",
          "year": 1932,
          "children": [
            {"name": "Quarks", "year": 1964, "summary": "Elementary particles that combine to form composite particles like protons and neutrons.", "people": ["Murray Gell-Mann", "George Zweig"], "nobel": 1969},
            {"name": "Leptons", "year": 1947, "summary": "Class of elementary particles that do not participate in strong interactions, including electrons and neutrinos.", "people": ["Cecil Powell"], "nobel": 1950},
            {"name": "Gauge Bosons", "year": 1983, "people": ["Carlo Rubbia", "Simon van der Meer"], "tags": [{"name": "force", "explanation": "These particles are the force carriers that mediate the fundamental forces: photons (electromagnetic), W and Z bosons (weak), and gluons (strong)."}], "nobel": 1984},
            {"name": "Higgs Boson", "year": 2012, "summary": "Elementary particle that gives mass to other particles through the Higgs field.", "people": ["Peter Higgs", "François Englert"], "nobel": 2013}
          ]
        },
        {
          "name": "Symmetries",
          "year": 1918,
          "children": [
            {"name": "Gauge Symmetry", "year": 1918, "summary": "Symmetry principle underlying the fundamental forces, describing invariance under local transformations.", "people": ["Hermann Weyl"]},
            {"name": "CP Violation", "year": 1964, "summary": "Violation of the combined symmetry of charge conjugation and parity, explaining matter-antimatter asymmetry.", "people": ["James Cronin", "Val Fitch"]},
            {"name": "Supersymmetry", "year": 1971, "summary": "Theoretical symmetry relating fermions and bosons, proposing a partner particle for each known particle.", "people": ["Yuri Golfand", "Evgeny Likhtman"]},
            {"name": "String Theory", "year": 1970, "summary": "Theoretical framework proposing that fundamental particles are one-dimensional vibrating strings rather than point particles.", "people": ["Yoichiro Nambu", "Holger Bech Nielsen", "Leonard Susskind"]}
          ]
        },
        {
          "name": "Accelerator Physics",
          "year": 1930,
          "children": [
            {"name": "Collider Experiments", "year": 1956, "summary": "Experiments using particle accelerators to collide particles at high energies to study fundamental physics.", "people": ["Donald Kerst"]},
            {"name": "Particle Detectors", "year": 1911, "summary": "Instruments designed to detect and measure properties of subatomic particles and radiation.", "people": ["Hans Geiger", "Ernest Rutherford"]},
            {"name": "Beam Dynamics", "year": 1950, "summary": "Study of the motion and control of charged particle beams in accelerators and storage rings.", "people": ["Ernest Courant", "Milton Livingston", "Hartland Snyder"]},
            {"name": "Synchrotron Radiation", "year": 1947, "summary": "Electromagnetic radiation emitted when charged particles are accelerated in curved paths, typically in synchrotrons.", "people": ["Elder", "Gurewitsch", "Langmuir"]}
          ]
        }
      ]
    }
  ]
};

// Nobel Prize in Physics awards by year
const nobelPrizes = {
  1901: "Wilhelm Conrad Röntgen - Discovery of X-rays",
  1902: "Hendrik Lorentz and Pieter Zeeman - Influence of magnetism upon radiation phenomena",
  1903: "Antoine Henri Becquerel, Pierre Curie, and Marie Curie - Discovery of spontaneous radioactivity",
  1904: "Lord Rayleigh - Density of gases and discovery of argon",
  1905: "Philipp Lenard - Work on cathode rays",
  1906: "Joseph John Thomson - Conduction of electricity by gases",
  1907: "Albert A. Michelson - Optical precision instruments and spectroscopic and metrological investigations",
  1908: "Gabriel Lippmann - Method of reproducing colours photographically based on the phenomenon of interference",
  1909: "Guglielmo Marconi and Karl Ferdinand Braun - Development of wireless telegraphy",
  1910: "Johannes Diderik van der Waals - Equation of state for gases and liquids",
  1911: "Wilhelm Wien - Laws governing the radiation of heat",
  1912: "Nils Gustaf Dalén - Automatic regulators for use in conjunction with gas accumulators for illuminating lighthouses and buoys",
  1913: "Heike Kamerlingh Onnes - Properties of matter at low temperatures, production of liquid helium",
  1914: "Max von Laue - Diffraction of X-rays by crystals",
  1915: "William Henry Bragg and William Lawrence Bragg - Analysis of crystal structure by means of X-rays",
  1916: "No prize awarded",
  1917: "Charles Glover Barkla - Discovery of the characteristic Röntgen radiation of the elements",
  1918: "Max Planck - Discovery of energy quanta",
  1919: "Johannes Stark - Discovery of the Doppler effect in canal rays and the splitting of spectral lines in electric fields",
  1920: "Charles Édouard Guillaume - Precision measurements in physics by his discovery of anomalies in nickel steel alloys",
  1921: "Albert Einstein - Photoelectric effect",
  1922: "Niels Bohr - Structure of atoms and radiation emanating from them",
  1923: "Robert Andrews Millikan - Work on the elementary charge of electricity and on the photoelectric effect",
  1924: "Manne Siegbahn - Discoveries and research in the field of X-ray spectroscopy",
  1925: "James Franck and Gustav Hertz - Laws governing the impact of an electron upon an atom",
  1926: "Jean Baptiste Perrin - Work on the discontinuous structure of matter, and especially for his discovery of sedimentation equilibrium",
  1927: "Arthur Holly Compton - Discovery of the effect named after him; Charles Thomson Rees Wilson - Method of making the paths of electrically charged particles visible by condensation of vapour",
  1928: "Owen Willans Richardson - Work on the thermionic phenomenon and especially for the discovery of the law named after him",
  1929: "Louis de Broglie - Discovery of the wave nature of electrons",
  1930: "Chandrasekhara Venkata Raman - Work on the scattering of light and for the discovery of the effect named after him",
  1931: "No prize awarded",
  1932: "Werner Heisenberg - Creation of quantum mechanics",
  1933: "Erwin Schrödinger and Paul Dirac - Discovery of new productive forms of atomic theory",
  1934: "No prize awarded",
  1935: "James Chadwick - Discovery of the neutron",
  1936: "Victor Franz Hess - Discovery of cosmic radiation; Carl David Anderson - Discovery of the positron",
  1937: "Clinton Joseph Davisson and George Paget Thomson - Experimental discovery of the diffraction of electrons by crystals",
  1938: "Enrico Fermi - Demonstrations of the existence of new radioactive elements produced by neutron irradiation, and for his related discovery of nuclear reactions brought about by slow neutrons",
  1939: "Ernest Lawrence - Invention and development of the cyclotron and for results obtained with it, especially with regard to artificial radioactive elements",
  1940: "No prize awarded",
  1941: "No prize awarded",
  1942: "No prize awarded",
  1943: "Otto Stern - Contribution to the development of the molecular ray method and his discovery of the magnetic moment of the proton",
  1944: "Isidor Isaac Rabi - Resonance method for recording the magnetic properties of atomic nuclei",
  1945: "Wolfgang Pauli - Discovery of the Exclusion Principle",
  1946: "Percy Williams Bridgman - Invention of an apparatus to produce extremely high pressures, and for the discoveries he made therewith in the field of high pressure physics",
  1947: "Edward Victor Appleton - Investigations of the physics of the upper atmosphere especially for the discovery of the so-called Appleton layer",
  1948: "Patrick Maynard Stuart Blackett - Development of the Wilson cloud chamber method, and his discoveries therewith in the fields of nuclear physics and cosmic radiation",
  1949: "Hideki Yukawa - Prediction of the existence of mesons on the basis of theoretical work on nuclear forces",
  1950: "Cecil Frank Powell - Development of the photographic method of studying nuclear processes and his discoveries regarding mesons made with this method",
  1951: "John Douglas Cockcroft and Ernest Thomas Sinton Walton - Pioneer work on the transmutation of atomic nuclei by artificially accelerated atomic particles",
  1952: "Felix Bloch and Edward Mills Purcell - Development of new methods for nuclear magnetic precision measurements and discoveries in connection therewith",
  1953: "Frits Zernike - Demonstration of the phase contrast method, especially for his invention of the phase contrast microscope",
  1954: "Max Born - Fundamental research in quantum mechanics, especially for his statistical interpretation of the wavefunction; Walther Bothe - Coincidence method and his discoveries made therewith",
  1955: "Willis Eugene Lamb - Discoveries concerning the fine structure of the hydrogen spectrum; Polykarp Kusch - Precision determination of the magnetic moment of the electron",
  1956: "John Bardeen, Walter Houser Brattain, and William Shockley - Research on semiconductors and their discovery of the transistor effect",
  1957: "Tsung-Dao Lee and Chen-Ning Yang - Discovery of violations of the principle of parity conservation",
  1958: "Pavel Alekseyevich Cherenkov, Il'ja Mikhailovich Frank, and Igor Yevgenyevich Tamm - Discovery and the interpretation of the Cherenkov effect",
  1959: "Emilio Gino Segrè and Owen Chamberlain - Discovery of the antiproton",
  1960: "Donald Arthur Glaser - Invention of the bubble chamber",
  1961: "Robert Hofstadter - Pioneering studies of electron scattering in atomic nuclei and for his thereby achieved discoveries concerning the structure of the nucleons; Rudolf Ludwig Mössbauer - Research concerning the resonance absorption of gamma radiation and his discovery in this connection of the effect which bears his name",
  1962: "Lev Davidovich Landau - Pioneering theories for condensed matter, especially liquid helium",
  1963: "Eugene Paul Wigner - Contributions to the theory of the atomic nucleus and the elementary particles, particularly through the discovery and application of fundamental symmetry principles; Maria Goeppert-Mayer and J. Hans D. Jensen - Discoveries concerning nuclear shell structure",
  1964: "Charles Hard Townes, Nikolay Gennadiyevich Basov, and Aleksandr Mikhailovich Prokhorov - Fundamental work in the field of quantum electronics, which has led to the construction of oscillators and amplifiers based on the maser-laser principle",
  1965: "Sin-Itiro Tomonaga, Julian Schwinger, and Richard P. Feynman - Fundamental work in quantum electrodynamics, with deep-ploughing consequences for the physics of elementary particles",
  1966: "Alfred Kastler - Discovery and development of optical methods for studying Hertzian resonances in atoms",
  1967: "Hans Albrecht Bethe - Contributions to the theory of nuclear reactions, especially his discoveries concerning the energy production in stars",
  1968: "Luis Walter Alvarez - Decisive contributions to elementary particle physics, in particular the discovery of a large number of resonance states, made possible through his development of the technique of using hydrogen bubble chamber and data analysis",
  1969: "Murray Gell-Mann - Contributions and discoveries concerning the classification of elementary particles and their interactions",
  1970: "Hannes Alfvén - Fundamental work and discoveries in magnetohydrodynamics with fruitful applications in different parts of plasma physics; Louis Néel - Fundamental work and discoveries concerning antiferromagnetism and ferrimagnetism which have led to important applications in solid state physics",
  1971: "Dennis Gabor - Invention and development of the holographic method",
  1972: "John Bardeen, Leon Neil Cooper, and John Robert Schrieffer - Jointly developed theory of superconductivity",
  1973: "Leo Esaki and Ivar Giaever - Experimental discoveries regarding tunneling phenomena in semiconductors and superconductors respectively; Brian David Josephson - Theoretical predictions of the properties of a supercurrent through a tunnel barrier",
  1974: "Martin Ryle and Antony Hewish - Pioneering research in radio astrophysics",
  1975: "Aage Niels Bohr, Ben Roy Mottelson, and Leo James Rainwater - Discovery of the connection between collective motion and particle motion in atomic nuclei and the development of the theory of the structure of the atomic nucleus based on this connection",
  1976: "Burton Richter and Samuel Chao Chung Ting - Pioneering work in the discovery of a heavy elementary particle of a new kind",
  1977: "Philip Warren Anderson, Nevill Francis Mott, and John Hasbrouck Van Vleck - Fundamental theoretical investigations of the electronic structure of magnetic and disordered systems",
  1978: "Pyotr Leonidovich Kapitsa - Basic inventions and discoveries in the area of low-temperature physics; Arno Allan Penzias and Robert Woodrow Wilson - Discovery of cosmic microwave background radiation",
  1979: "Sheldon Lee Glashow, Abdus Salam, and Steven Weinberg - Contributions to the theory of the unified weak and electromagnetic interaction between elementary particles",
  1980: "James Watson Cronin and Val Logsdon Fitch - Discovery of violations of fundamental symmetry principles in the decay of neutral K-mesons",
  1981: "Nicolaas Bloembergen and Arthur Leonard Schawlow - Development of laser spectroscopy; Kai Manne Börje Siegbahn - Contribution to the development of high-resolution electron spectroscopy",
  1982: "Kenneth G. Wilson - Theory for critical phenomena in connection with phase transitions",
  1983: "Subrahmanyan Chandrasekhar - Theoretical studies of the physical processes of importance to the structure and evolution of the stars; William Alfred Fowler - Theoretical and experimental studies of the nuclear reactions of importance in the formation of the chemical elements in the universe",
  1984: "Carlo Rubbia and Simon van der Meer - Decisive contributions to the large project, which led to the discovery of the field particles W and Z, communicators of weak interaction",
  1985: "Klaus von Klitzing - Discovery of the quantized Hall effect",
  1986: "Ernst Ruska - Fundamental work in electron optics, and for the design of the first electron microscope; Gerd Binnig and Heinrich Rohrer - Design of the scanning tunneling microscope",
  1987: "J. Georg Bednorz and K. Alexander Müller - Important breakthrough in the discovery of superconductivity in ceramic materials",
  1988: "Leon M. Lederman, Melvin Schwartz, and Jack Steinberger - Neutrino beam method and the demonstration of the doublet structure of the leptons through the discovery of the muon neutrino",
  1989: "Norman F. Ramsey - Invention of the separated oscillatory fields method and its use in the hydrogen maser and other atomic clocks; Hans G. Dehmelt and Wolfgang Paul - Development of the ion trap technique",
  1990: "Jerome I. Friedman, Henry W. Kendall, and Richard E. Taylor - Pioneering investigations concerning deep inelastic scattering of electrons on protons and bound neutrons",
  1991: "Pierre-Gilles de Gennes - Discovering that methods developed for studying order phenomena in simple systems can be generalized to more complex forms of matter",
  1992: "Georges Charpak - Invention and development of particle detectors, in particular the multiwire proportional chamber",
  1993: "Russell A. Hulse and Joseph H. Taylor Jr. - Discovery of a new type of pulsar, a discovery that has opened up new possibilities for the study of gravitation",
  1994: "Bertram N. Brockhouse - Development of neutron spectroscopy; Clifford G. Shull - Development of the neutron diffraction technique",
  1995: "Martin L. Perl - Discovery of the tau lepton; Frederick Reines - Detection of the neutrino",
  1996: "David M. Lee, Douglas D. Osheroff, and Robert C. Richardson - Discovery of superfluidity in helium-3",
  1997: "Steven Chu, Claude Cohen-Tannoudji, and William D. Phillips - Development of methods to cool and trap atoms with laser light",
  1998: "Robert B. Laughlin, Horst L. Störmer, and Daniel C. Tsui - Discovery of a new form of quantum fluid with fractionally charged excitations",
  1999: "Gerardus 't Hooft and Martinus J. G. Veltman - Elucidating the quantum structure of electroweak interactions in physics",
  2000: "Zhores I. Alferov and Herbert Kroemer - Developing semiconductor heterostructures used in high-speed- and opto-electronics; Jack S. Kilby - Part in the invention of the integrated circuit",
  2001: "Eric A. Cornell, Wolfgang Ketterle, and Carl E. Wieman - Achievement of Bose-Einstein condensation in dilute gases of alkali atoms, and for early fundamental studies of the properties of the condensates",
  2002: "Raymond Davis Jr. and Masatoshi Koshiba - Pioneering contributions to astrophysics, in particular for the detection of cosmic neutrinos; Riccardo Giacconi - Pioneering contributions to astrophysics, which have led to the discovery of cosmic X-ray sources",
  2003: "Alexei A. Abrikosov, Vitaly L. Ginzburg, and Anthony J. Leggett - Pioneering contributions to the theory of superconductors and superfluids",
  2004: "David J. Gross, H. David Politzer, and Frank Wilczek - Discovery of asymptotic freedom in the theory of the strong interaction",
  2005: "Roy J. Glauber - Contribution to the quantum theory of optical coherence; John L. Hall and Theodor W. Hänsch - Contributions to the development of laser-based precision spectroscopy",
  2006: "John C. Mather and George F. Smoot - Discovery of the blackbody form and anisotropy of the cosmic microwave background radiation",
  2007: "Albert Fert and Peter Grünberg - Discovery of giant magnetoresistance",
  2008: "Makoto Kobayashi and Toshihide Maskawa - Discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature; Yoichiro Nambu - Discovery of the mechanism of spontaneous broken symmetry in subatomic physics",
  2009: "Charles K. Kao - Groundbreaking achievements concerning the transmission of light in fibers for optical communication; Willard S. Boyle and George E. Smith - Invention of an imaging semiconductor circuit – the CCD sensor",
  2010: "Andre Geim and Konstantin Novoselov - Groundbreaking experiments regarding the two-dimensional material graphene",
  2011: "Saul Perlmutter, Brian P. Schmidt, and Adam G. Riess - Discovery of the accelerating expansion of the Universe through observations of distant supernovae",
  2012: "Serge Haroche and David J. Wineland - Ground-breaking experimental methods that enable measuring and manipulation of individual quantum systems",
  2013: "François Englert and Peter W. Higgs - Theoretical discovery of a mechanism that contributes to our understanding of the origin of mass of subatomic particles",
  2014: "Isamu Akasaki, Hiroshi Amano, and Shuji Nakamura - Invention of efficient blue light-emitting diodes which has enabled bright and energy-saving white light sources",
  2015: "Takaaki Kajita and Arthur B. McDonald - Discovery of neutrino oscillations, which shows that neutrinos have mass",
  2016: "David J. Thouless, F. Duncan M. Haldane, and J. Michael Kosterlitz - Theoretical discoveries of topological phase transitions and topological phases of matter",
  2017: "Rainer Weiss, Barry C. Barish, and Kip S. Thorne - Decisive contributions to the LIGO detector and the observation of gravitational waves",
  2018: "Arthur Ashkin - Optical tweezers and their application to biological systems; Gérard Mourou and Donna Strickland - Method of generating high-intensity, ultra-short optical pulses",
  2019: "James Peebles - Theoretical discoveries in physical cosmology; Michel Mayor and Didier Queloz - Discovery of an exoplanet orbiting a solar-type star",
  2020: "Roger Penrose - Discovery that black hole formation is a robust prediction of the general theory of relativity; Reinhard Genzel and Andrea Ghez - Discovery of a supermassive compact object at the centre of our galaxy",
  2021: "Syukuro Manabe and Klaus Hasselmann - Physical modelling of Earth's climate, quantifying variability and reliably predicting global warming; Giorgio Parisi - Discovery of the interplay of disorder and fluctuations in physical systems from atomic to planetary scales",
  2022: "Alain Aspect, John F. Clauser, and Anton Zeilinger - Experiments with entangled photons, establishing the violation of Bell inequalities and pioneering quantum information science",
  2023: "Pierre Agostini, Ferenc Krausz, and Anne L'Huillier - Experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter",
  2024: "John F. Clauser, Alain Aspect, and Anton Zeilinger - For experiments with entangled photons, establishing the violation of Bell inequalities and pioneering quantum information science"
};

// Nobel Prize years for people (array of years they won)
const peopleNobel = {
  "Wilhelm Conrad Röntgen": [1901],
  "Hendrik Lorentz": [1902],
  "Pieter Zeeman": [1902],
  "Antoine Henri Becquerel": [1903],
  "Pierre Curie": [1903],
  "Marie Curie": [1903],
  "Lord Rayleigh": [1904],
  "Philipp Lenard": [1905],
  "Joseph John Thomson": [1906],
  "Albert A. Michelson": [1907],
  "Gabriel Lippmann": [1908],
  "Guglielmo Marconi": [1909],
  "Karl Ferdinand Braun": [1909],
  "Johannes Diderik van der Waals": [1910],
  "Wilhelm Wien": [1911],
  "Nils Gustaf Dalén": [1912],
  "Heike Kamerlingh Onnes": [1913],
  "Max von Laue": [1914],
  "William Henry Bragg": [1915],
  "William Lawrence Bragg": [1915],
  "Charles Glover Barkla": [1917],
  "Max Planck": [1918],
  "Johannes Stark": [1919],
  "Charles Édouard Guillaume": [1920],
  "Albert Einstein": [1921],
  "Niels Bohr": [1922],
  "Robert Andrews Millikan": [1923],
  "Manne Siegbahn": [1924],
  "James Franck": [1925],
  "Gustav Hertz": [1925],
  "Jean Baptiste Perrin": [1926],
  "Arthur Holly Compton": [1927],
  "Charles Thomson Rees Wilson": [1927],
  "Owen Willans Richardson": [1928],
  "Louis de Broglie": [1929],
  "Chandrasekhara Venkata Raman": [1930],
  "Werner Heisenberg": [1932],
  "Erwin Schrödinger": [1933],
  "Paul Dirac": [1933],
  "James Chadwick": [1935],
  "Victor Franz Hess": [1936],
  "Carl David Anderson": [1936],
  "Clinton Joseph Davisson": [1937],
  "George Paget Thomson": [1937],
  "Enrico Fermi": [1938],
  "Ernest Lawrence": [1939],
  "Otto Stern": [1943],
  "Isidor Isaac Rabi": [1944],
  "Wolfgang Pauli": [1945],
  "Percy Williams Bridgman": [1946],
  "Edward Victor Appleton": [1947],
  "Patrick Maynard Stuart Blackett": [1948],
  "Hideki Yukawa": [1949],
  "Cecil Powell": [1950],
  "John Douglas Cockcroft": [1951],
  "Ernest Thomas Sinton Walton": [1951],
  "Felix Bloch": [1952],
  "Edward Mills Purcell": [1952],
  "Frits Zernike": [1953],
  "Max Born": [1954],
  "Walther Bothe": [1954],
  "Willis Eugene Lamb": [1955],
  "Polykarp Kusch": [1955],
  "John Bardeen": [1956, 1972],
  "Walter Houser Brattain": [1956],
  "William Shockley": [1956],
  "Tsung-Dao Lee": [1957],
  "Chen-Ning Yang": [1957],
  "Pavel Alekseyevich Cherenkov": [1958],
  "Il'ja Mikhailovich Frank": [1958],
  "Igor Yevgenyevich Tamm": [1958],
  "Emilio Gino Segrè": [1959],
  "Owen Chamberlain": [1959],
  "Donald Arthur Glaser": [1960],
  "Robert Hofstadter": [1961],
  "Rudolf Ludwig Mössbauer": [1961],
  "Lev Davidovich Landau": [1962],
  "Eugene Paul Wigner": [1963],
  "Maria Goeppert-Mayer": [1963],
  "J. Hans D. Jensen": [1963],
  "Charles Hard Townes": [1964],
  "Nikolay Gennadiyevich Basov": [1964],
  "Aleksandr Mikhailovich Prokhorov": [1964],
  "Sin-Itiro Tomonaga": [1965],
  "Julian Schwinger": [1965],
  "Richard P. Feynman": [1965],
  "Richard Feynman": [1965],
  "Alfred Kastler": [1966],
  "Hans Albrecht Bethe": [1967],
  "Luis Walter Alvarez": [1968],
  "Murray Gell-Mann": [1969],
  "Hannes Alfvén": [1970],
  "Louis Néel": [1970],
  "Dennis Gabor": [1971],
  "Leon Neil Cooper": [1972],
  "John Robert Schrieffer": [1972],
  "Leo Esaki": [1973],
  "Ivar Giaever": [1973],
  "Brian David Josephson": [1973],
  "Martin Ryle": [1974],
  "Antony Hewish": [1974],
  "Aage Niels Bohr": [1975],
  "Ben Roy Mottelson": [1975],
  "Leo James Rainwater": [1975],
  "Burton Richter": [1976],
  "Samuel Chao Chung Ting": [1976],
  "Philip Warren Anderson": [1977],
  "Nevill Francis Mott": [1977],
  "John Hasbrouck Van Vleck": [1977],
  "Pyotr Leonidovich Kapitsa": [1978],
  "Arno Allan Penzias": [1978],
  "Robert Woodrow Wilson": [1978],
  "Sheldon Lee Glashow": [1979],
  "Sheldon Glashow": [1979],
  "Abdus Salam": [1979],
  "Steven Weinberg": [1979],
  "James Watson Cronin": [1980],
  "Val Logsdon Fitch": [1980],
  "Nicolaas Bloembergen": [1981],
  "Arthur Leonard Schawlow": [1981],
  "Kai Manne Börje Siegbahn": [1981],
  "Kenneth G. Wilson": [1982],
  "Subrahmanyan Chandrasekhar": [1983],
  "William Alfred Fowler": [1983],
  "Carlo Rubbia": [1984],
  "Simon van der Meer": [1984],
  "Klaus von Klitzing": [1985],
  "Ernst Ruska": [1986],
  "Gerd Binnig": [1986],
  "Heinrich Rohrer": [1986],
  "J. Georg Bednorz": [1987],
  "K. Alexander Müller": [1987],
  "Leon M. Lederman": [1988],
  "Melvin Schwartz": [1988],
  "Jack Steinberger": [1988],
  "Norman F. Ramsey": [1989],
  "Hans G. Dehmelt": [1989],
  "Wolfgang Paul": [1989],
  "Jerome I. Friedman": [1990],
  "Henry W. Kendall": [1990],
  "Richard E. Taylor": [1990],
  "Pierre-Gilles de Gennes": [1991],
  "Georges Charpak": [1992],
  "Russell A. Hulse": [1993],
  "Joseph H. Taylor Jr.": [1993],
  "Bertram N. Brockhouse": [1994],
  "Clifford G. Shull": [1994],
  "Martin L. Perl": [1995],
  "Frederick Reines": [1995],
  "David M. Lee": [1996],
  "Douglas D. Osheroff": [1996],
  "Robert C. Richardson": [1996],
  "Steven Chu": [1997],
  "Claude Cohen-Tannoudji": [1997],
  "William D. Phillips": [1997],
  "Robert B. Laughlin": [1998],
  "Horst L. Störmer": [1998],
  "Daniel C. Tsui": [1998],
  "Gerardus 't Hooft": [1999],
  "Martinus J. G. Veltman": [1999],
  "Zhores I. Alferov": [2000],
  "Herbert Kroemer": [2000],
  "Jack S. Kilby": [2000],
  "Eric A. Cornell": [2001],
  "Wolfgang Ketterle": [2001],
  "Carl E. Wieman": [2001],
  "Raymond Davis Jr.": [2002],
  "Masatoshi Koshiba": [2002],
  "Riccardo Giacconi": [2002],
  "Alexei A. Abrikosov": [2003],
  "Vitaly L. Ginzburg": [2003],
  "Anthony J. Leggett": [2003],
  "David J. Gross": [2004],
  "H. David Politzer": [2004],
  "Frank Wilczek": [2004],
  "Roy J. Glauber": [2005],
  "John L. Hall": [2005],
  "Theodor W. Hänsch": [2005],
  "John C. Mather": [2006],
  "George F. Smoot": [2006],
  "Albert Fert": [2007],
  "Peter Grünberg": [2007],
  "Makoto Kobayashi": [2008],
  "Toshihide Maskawa": [2008],
  "Yoichiro Nambu": [2008],
  "Charles K. Kao": [2009],
  "Willard S. Boyle": [2009],
  "George E. Smith": [2009],
  "Andre Geim": [2010],
  "Konstantin Novoselov": [2010],
  "Saul Perlmutter": [2011],
  "Brian P. Schmidt": [2011],
  "Adam G. Riess": [2011],
  "Serge Haroche": [2012],
  "David J. Wineland": [2012],
  "François Englert": [2013],
  "Peter W. Higgs": [2013],
  "Peter Higgs": [2013],
  "Isamu Akasaki": [2014],
  "Hiroshi Amano": [2014],
  "Shuji Nakamura": [2014],
  "Takaaki Kajita": [2015],
  "Arthur B. McDonald": [2015],
  "David J. Thouless": [2016],
  "F. Duncan M. Haldane": [2016],
  "J. Michael Kosterlitz": [2016],
  "Rainer Weiss": [2017],
  "Barry C. Barish": [2017],
  "Kip S. Thorne": [2017],
  "Arthur Ashkin": [2018],
  "Gérard Mourou": [2018],
  "Donna Strickland": [2018],
  "James Peebles": [2019],
  "Michel Mayor": [2019],
  "Didier Queloz": [2019],
  "Roger Penrose": [2020],
  "Reinhard Genzel": [2020],
  "Andrea Ghez": [2020],
  "Syukuro Manabe": [2021],
  "Klaus Hasselmann": [2021],
  "Giorgio Parisi": [2021],
  "Alain Aspect": [2022],
  "John F. Clauser": [2022],
  "Anton Zeilinger": [2022],
  "Pierre Agostini": [2023],
  "Ferenc Krausz": [2023],
  "Anne L'Huillier": [2023]
};
